spring:
  #Datasource configuration (database connection)
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: "root"
    password: "123"
  #JPA-Hibernate configuration
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
